version: "3.8"

x-shared-settings: &shared-settings
  env_file: ./server/.env
  restart: unless-stopped
  stdin_open: true
  tty: true

# - `build.context`
#   - 相對於執行 docker-compose 指令時的路徑
# - `build.dockerfile`
#   - 相對於 context 的路徑值，以此路徑來指定 dockerfile ，而 dockerfile 內則以 context 為基礎路徑進行配置
# - `networks`
#   - 在 docker-compose.network 預計要先被啟動，不然會報錯。
services:
  backend:
    <<: *shared-settings
    build:
      context: server
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./server/src:/app/server/src
    networks:
      - frontend
      - backend
    depends_on:
      # - postgres
      - redis-node1
      #- redis-node2
      #- redis-node3

  # postgres:
  #   <<: *shared-settings
  #   build:
  #     context: server
  #     dockerfile: docker/postgresql/Dockerfile
  #     args:
  #       POSTGRES_IMAGE: $POSTGRES_IMAGE
  #   container_name: $POSTGRES_HOST
  #   volumes:
  #     - ./server/docker/postgresql/data:/data
  #   ports:
  #     - $POSTGRES_PORT:$POSTGRES_CONTAINER_PORT
  #   networks:
  #     - backend

  redis-node1:
    <<: *shared-settings
    build:
      context: server
      dockerfile: docker/redis/Dockerfile
    container_name: $REDIS_HOST1
    volumes:
      - ./server/docker/redis/data/node1:/data
    ports:
      - ${REDIS_PORT1}:${REDIS_CONTAINER_PORT}
    networks:
      - backend

  # redis-node2:
  #   <<: *shared-settings
  #   build:
  #     context: server
  #     dockerfile: docker/redis/Dockerfile
  #   container_name: $REDIS_HOST2
  #   volumes:
  #     - ./server/docker/redis/data/node2:/data
  #   ports:
  #     - ${REDIS_PORT2}:${REDIS_CONTAINER_PORT}
  #   networks:
  #     - backend
  #
  # redis-node3:
  #   <<: *shared-settings
  #   build:
  #     context: server
  #     dockerfile: docker/redis/Dockerfile
  #   container_name: $REDIS_HOST3
  #   volumes:
  #     - ./server/docker/redis/data/node3:/data
  #   ports:
  #     - ${REDIS_PORT3}:${REDIS_CONTAINER_PORT}
  #   networks:
  #     - backend
