version: "3.8"

# - `build.context`
#   - 相對於執行 docker-compose 指令時的路徑
# - `build.dockerfile`
#   - 相對於 context 的路徑值，以此路徑來指定 dockerfile ，而 dockerfile 內則以 context 為基礎路徑進行配置
# - `networks`
#   - 在 docker-compose.network 預計要先被啟動，不然會報錯。
services:
  backend:
    container_name: backend
    build:
      context: server
      dockerfile: docker/Dockerfile
    env_file: ./server/.env
    restart: on-failure:10
    stdin_open: true
    tty: true
    networks:
      - frontend
      - backend
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    volumes:
      - ./server/src:/app/server/src
    depends_on:
      - postgres
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
