version: "3.8"

x-shared-settings: &shared-settings
  env_file: ./server/.env
  restart: unless-stopped
  stdin_open: true
  tty: true
  networks:
    - backend

# - `build.context`
#   - 相對於執行 docker-compose 指令時的路徑
# - `build.dockerfile`
#   - 相對於 context 的路徑值，以此路徑來指定 dockerfile ，而 dockerfile 內則以 context 為基礎路徑進行配置
# - `networks`
#   - 在 docker-compose.network 預計要先被啟動，不然會報錯。
services:
  backend:
    <<: *shared-settings
    build:
      context: server
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    volumes:
      - ./server/src:/app/server/src
    networks:
      - frontend
      - backend
    depends_on:
      # - postgres
      - redis-cluster

  # postgres:
  #   <<: *shared-settings
  #   build:
  #     context: server
  #     dockerfile: docker/postgresql/Dockerfile
  #     args:
  #       POSTGRES_IMAGE: $POSTGRES_IMAGE
  #   container_name: $POSTGRES_HOST
  #   volumes:
  #     - ./server/docker/postgresql/data:/data
  #   ports:
  #     - $POSTGRES_PORT:$POSTGRES_CONTAINER_PORT
  #   networks:
  #     - backend

  redis-cluster:
    <<: *shared-settings
    restart: on-failure:5
    image: $REDIS_IMAGE
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
    volumes:
      - ./server/docker/redis/create-cluster.sh:/redis-cluster-setup.sh
    command: sh /redis-cluster-setup.sh;

  redis-node1:
    <<: *shared-settings
    container_name: $REDIS_HOST1
    image: $REDIS_IMAGE
    volumes:
      - ./server/docker/redis/data/node1:/data
    ports:
      - $REDIS_PORT1:$REDIS_PORT1
    command: |
      sh -c 'redis-server \
        --requirepass $REDIS_PASSWORD \
        --masterauth $REDIS_PASSWORD \
        --port $REDIS_PORT1 \
        --cluster-enabled yes \
        --cluster-node-timeout 5000 \
        --appendonly yes'

  redis-node2:
    <<: *shared-settings
    container_name: $REDIS_HOST2
    image: $REDIS_IMAGE
    volumes:
      - ./server/docker/redis/data/node2:/data
    ports:
      - $REDIS_PORT2:$REDIS_PORT2
    command: |
      sh -c 'redis-server \
        --requirepass $REDIS_PASSWORD \
        --masterauth $REDIS_PASSWORD \
        --port $REDIS_PORT2 \
        --cluster-enabled yes \
        --cluster-node-timeout 5000 \
        --appendonly yes'

  redis-node3:
    <<: *shared-settings
    container_name: $REDIS_HOST3
    image: $REDIS_IMAGE
    volumes:
      - ./server/docker/redis/data/node3:/data
    ports:
      - $REDIS_PORT3:$REDIS_PORT3
    command: |
      sh -c 'redis-server \
        --requirepass $REDIS_PASSWORD \
        --masterauth $REDIS_PASSWORD \
        --port $REDIS_PORT3 \
        --cluster-enabled yes \
        --cluster-node-timeout 5000 \
        --appendonly yes'

  redis-node4:
    <<: *shared-settings
    container_name: $REDIS_HOST4
    image: $REDIS_IMAGE
    volumes:
      - ./server/docker/redis/data/node4:/data
    ports:
      - $REDIS_PORT4:$REDIS_PORT4
    command: |
      sh -c 'redis-server \
        --requirepass $REDIS_PASSWORD \
        --masterauth $REDIS_PASSWORD \
        --port $REDIS_PORT4 \
        --cluster-enabled yes \
        --cluster-node-timeout 5000 \
        --appendonly yes'

  redis-node5:
    <<: *shared-settings
    container_name: $REDIS_HOST5
    image: $REDIS_IMAGE
    volumes:
      - ./server/docker/redis/data/node5:/data
    ports:
      - $REDIS_PORT5:$REDIS_PORT5
    command: |
      sh -c 'redis-server \
        --requirepass $REDIS_PASSWORD \
        --masterauth $REDIS_PASSWORD \
        --port $REDIS_PORT5 \
        --cluster-enabled yes \
        --cluster-node-timeout 5000 \
        --appendonly yes'

  redis-node6:
    <<: *shared-settings
    container_name: $REDIS_HOST6
    image: $REDIS_IMAGE
    volumes:
      - ./server/docker/redis/data/node6:/data
    ports:
      - $REDIS_PORT6:$REDIS_PORT6
    command: |
      sh -c 'redis-server \
        --requirepass $REDIS_PASSWORD \
        --masterauth $REDIS_PASSWORD \
        --port $REDIS_PORT6 \
        --cluster-enabled yes \
        --cluster-node-timeout 5000 \
        --appendonly yes'
