version: "3.8"

x-exec-settings: &exec-settings
  stdin_open: true
  tty: true

services:
  frontend:
    build:
      context: ../.. # 以 client folder 作為 context
      dockerfile: ./docker/Dockerfile # 以 context 的值來指定 dockerfile 的相對路徑. 而 dockerfile 內則以 context 為基礎路徑進行配置
    container_name: frontend
    env_file: .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ../..:/app/client
    networks: # 在 docker-compose.network 預計要先被啟動，不然會報錯
      - frontend
    depends_on:
      - backend # 在 server folder，預計要先被啟動，不然 frontend 會報錯
    restart: unless-stopped
    <<: *exec-settings
